//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub role: String,
    pub is_active: bool,
    pub email_verified: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::kyc_records::Entity")]
    KycRecords,
    #[sea_orm(has_many = "super::token_balances::Entity")]
    TokenBalances,
    #[sea_orm(has_many = "super::operations::Entity")]
    Operations,
}

impl Related<super::kyc_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KycRecords.def()
    }
}

impl Related<super::token_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenBalances.def()
    }
}

impl Related<super::operations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Operations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}